### ISSUE TITLE
Failed to switch to language error after kernel interrupt

### ISSUE THREAD

**Issue by j-andrews7** [vatlab/sos-notebook#126]
I've been running into an annoying issue sometimes after interrupting the kernel while running R code. When I try to run another cell with R code with the R kernel specified, I get an error:

`Failed to switch to language SoS: list index out of range`

If I run it again, I get an array of what seems to be all of my current R objects in memory.
```R
[ r"""base""",r"""categorize.peaks""",r"""ces""",r"""ces_anno""",r"""ces_nose""",r"""ces_se""",r"""ChIPseekerEnv""",r"""dfs""",r"""find.diffPeaks""",r"""g1""",r"""g2""",r"""hits""",r"""mark""",r"""nsamps""",r"""peaks""",r"""process.dbs""",r"""process.SEs""",r"""proms""",r"""proms_nose""",r"""proms_se""",r"""results""",r"""run.enrichments""",r"""samplesheet""",r"""ses""",r"""se_samplesheet""",r"""test""" ]
```

Running any existing cells after this will just alternate between those two outputs. Doesn't occur all the time and will occasionally go away after flashing each of them once. Creating a new cell and running anything (a function, assigning a variable, etc) will either work or seemingly try to run all the previous code from other cells that have given the above error, eventually crashing the kernel and forcing a restart. The traceback on the command line is due to an issue in `zmq` called from `tornado`. I don't have a deep enough understanding of what's occurring under the hood to speculate much further.

Traceback:
```bash
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 281, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 232, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 397, in execute_request
    user_expressions, allow_stdin)
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/sos_notebook/kernel.py", line 2480, in do_execute
    self.switch_kernel(self._meta['default_kernel'])
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/sos_notebook/kernel.py", line 1596, in switch_kernel
    self.handle_magic_put(self._kernel_return_vars)
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/sos_notebook/kernel.py", line 1898, in handle_magic_put
    items, to_kernel='SoS')
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/sos_r/kernel.py", line 323, in put_vars
    response = self.sos_kernel.get_response('cat(..py.repr(ls()))', ('stream',), name=('stdout',))[0][1]
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/sos_notebook/kernel.py", line 1836, in get_response
    while self.KC.iopub_channel.msg_ready():
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 71, in msg_ready
    return bool(self.socket.poll(timeout=0))
  File "/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/zmq/sugar/socket.py", line 689, in poll
    if self.closed:
  File "zmq/backend/cython/socket.pyx", line 356, in zmq.backend.cython.socket.Socket.closed.__get__
  File "zmq/backend/cython/socket.pyx", line 157, in zmq.backend.cython.socket._check_closed_deep
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
```

Ultimately, restarting the kernel isn't really a big deal, but it's annoying when your code takes a while to run if you don't want to constantly save variables to files. I recognize this is kind of edge behavior that might be hard to replicate, but I figured I'd report it in case you had any insights.

I'm running python 3.6.2, R 3.4.4, and jupyter notebook 5.6.0. SOS package versions:
```bash
sos                               0.9.16.8
sos-bash                          0.9.12.2
sos-bioinfo                       0.9.10.1
sos-essentials                    0.9.9.2
sos-javascript                    0.9.12.2
sos-julia                         0.9.12.1
sos-matlab                        0.9.12.1
sos-notebook                      0.9.16.3
sos-pbs                           0.9.10.3
sos-python                        0.9.12.1
sos-r                             0.9.12.3
sos-rq                            0.9.16.1
sos-ruby                          0.9.15.0
sos-sas                           0.9.12.3
```

My R session info is:

```R
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils    
 [8] datasets  methods   base     

other attached packages:
 [1] eulerr_4.1.0                           
 [2] viridis_0.5.1                          
 [3] viridisLite_0.3.0                      
 [4] venn_1.7                               
 [5] ReactomePA_1.22.0                      
 [6] clusterProfiler_3.6.0                  
 [7] DOSE_3.4.0                             
 [8] dplyr_0.7.4                            
 [9] org.Hs.eg.db_3.5.0                     
[10] GenomicAlignments_1.14.2               
[11] Rsamtools_1.30.0                       
[12] Biostrings_2.46.0                      
[13] XVector_0.18.0                         
[14] readr_1.1.1                            
[15] tximport_1.6.0                         
[16] RColorBrewer_1.1-2                     
[17] pheatmap_1.0.8                         
[18] TxDb.Hsapiens.UCSC.hg19.knownGene_3.2.2
[19] GenomicFeatures_1.30.3                 
[20] AnnotationDbi_1.40.0                   
[21] plotly_4.8.0                           
[22] ChIPseeker_1.14.2                      
[23] ChIPQC_1.14.0                          
[24] DiffBind_2.6.6                         
[25] SummarizedExperiment_1.8.1             
[26] DelayedArray_0.4.1                     
[27] matrixStats_0.53.1                     
[28] Biobase_2.38.0                         
[29] GenomicRanges_1.30.3                   
[30] GenomeInfoDb_1.14.0                    
[31] IRanges_2.12.0                         
[32] S4Vectors_0.16.0                       
[33] BiocGenerics_0.24.0                    
[34] ggplot2_3.0.0                          

loaded via a namespace (and not attached):
  [1] uuid_0.1-2                               
  [2] backports_1.1.2                          
  [3] GOstats_2.44.0                           
  [4] fastmatch_1.1-0                          
  [5] plyr_1.8.4                               
  [6] igraph_1.2.2                             
  [7] repr_0.15.0                              
  [8] lazyeval_0.2.1                           
  [9] GSEABase_1.40.1                          
 [10] splines_3.4.4                            
 [11] BatchJobs_1.7                            
 [12] BiocParallel_1.12.0                      
 [13] gridBase_0.4-7                           
 [14] amap_0.8-14                              
 [15] digest_0.6.16                            
 [16] htmltools_0.3.6                          
 [17] GOSemSim_2.4.1                           
 [18] GO.db_3.5.0                              
 [19] gdata_2.18.0                             
 [20] magrittr_1.5                             
 [21] checkmate_1.8.5                          
 [22] memoise_1.1.0                            
 [23] BBmisc_1.11                              
 [24] limma_3.34.9                             
 [25] annotate_1.56.2                          
 [26] Nozzle.R1_1.1-1                          
 [27] systemPipeR_1.12.0                       
 [28] prettyunits_1.0.2                        
 [29] colorspace_1.3-2                         
 [30] rappdirs_0.3.1                           
 [31] blob_1.1.1                               
 [32] ggrepel_0.8.0                            
 [33] crayon_1.3.4                             
 [34] RCurl_1.95-4.11                          
 [35] jsonlite_1.5                             
 [36] graph_1.56.0                             
 [37] chipseq_1.28.0                           
 [38] genefilter_1.60.0                        
 [39] bindr_0.1.1                              
 [40] brew_1.0-6                               
 [41] survival_2.42-3                          
 [42] sendmailR_1.2-1                          
 [43] glue_1.2.0                               
 [44] gtable_0.2.0                             
 [45] zlibbioc_1.24.0                          
 [46] UpSetR_1.3.3                             
 [47] graphite_1.24.1                          
 [48] Rgraphviz_2.22.0                         
 [49] scales_0.5.0                             
 [50] DBI_1.0.0                                
 [51] edgeR_3.20.9                             
 [52] TxDb.Mmusculus.UCSC.mm9.knownGene_3.2.2  
 [53] Rcpp_0.12.16                             
 [54] plotrix_3.7-3                            
 [55] xtable_1.8-2                             
 [56] progress_1.2.0                           
 [57] reactome.db_1.62.0                       
 [58] bit_1.1-12                               
 [59] AnnotationForge_1.20.0                   
 [60] htmlwidgets_1.2                          
 [61] httr_1.3.1                               
 [62] fgsea_1.4.1                              
 [63] gplots_3.0.1                             
 [64] pkgconfig_2.0.2                          
 [65] XML_3.98-1.16                            
 [66] locfit_1.5-9.1                           
 [67] rlang_0.2.2                              
 [68] reshape2_1.4.3                           
 [69] munsell_0.4.3                            
 [70] tools_3.4.4                              
 [71] RSQLite_2.1.1                            
 [72] evaluate_0.11                            
 [73] stringr_1.3.0                            
 [74] bit64_0.9-7                              
 [75] caTools_1.17.1                           
 [76] purrr_0.2.5                              
 [77] bindrcpp_0.2.2                           
 [78] RBGL_1.54.0                              
 [79] TxDb.Rnorvegicus.UCSC.rn4.ensGene_3.2.2  
 [80] DO.db_2.9                                
 [81] biomaRt_2.34.2                           
 [82] compiler_3.4.4                           
 [83] tibble_1.4.2                             
 [84] stringi_1.2.2                            
 [85] TxDb.Hsapiens.UCSC.hg18.knownGene_3.2.2  
 [86] lattice_0.20-35                          
 [87] IRdisplay_0.5.0                          
 [88] Matrix_1.2-14                            
 [89] pillar_1.2.2                             
 [90] data.table_1.11.2                        
 [91] bitops_1.0-6                             
 [92] TxDb.Mmusculus.UCSC.mm10.knownGene_3.4.0 
 [93] TxDb.Celegans.UCSC.ce6.ensGene_3.2.2     
 [94] rtracklayer_1.38.3                       
 [95] qvalue_2.10.0                            
 [96] R6_2.2.2                                 
 [97] latticeExtra_0.6-28                      
 [98] hwriter_1.3.2                            
 [99] RMySQL_0.10.15                           
[100] ShortRead_1.36.1                         
[101] KernSmooth_2.23-15                       
[102] gridExtra_2.3                            
[103] boot_1.3-20                              
[104] gtools_3.5.0                             
[105] assertthat_0.2.0                         
[106] Category_2.44.0                          
[107] rjson_0.2.18                             
[108] withr_2.1.2                              
[109] GenomeInfoDbData_1.0.0                   
[110] hms_0.4.2                                
[111] IRkernel_0.8.12.9000                     
[112] tidyr_0.8.1                              
[113] TxDb.Dmelanogaster.UCSC.dm3.ensGene_3.2.2
[114] rvcheck_0.1.0                            
[115] pbdZMQ_0.3-3                             
[116] base64enc_0.1-3                      
```

**Comment by BoPeng** [comment]
This might be the same problem as https://github.com/vatlab/sos-notebook/issues/109. Could you upgrade sos and sos-notebook to the latest version and let me know if the problem persists? Note that we have switched to 3-number version string so you should upgrade to sos 0.16.10 and sos 0.16.11.

**Comment by j-andrews7** [comment]
I will give that a try and report back, thanks.

**Comment by j-andrews7** [comment]
Updating resolved this, thanks!
