### ISSUE TITLE
Open existing notebook in sos

### ISSUE THREAD

**Issue by jma7** [vatlab/sos-notebook#199]
@BoPeng I still have difficulty in opening Gao's notebook (https://github.com/gaow/ismb-2018/blob/master/VAT-ISMB-2018.ipynb)  in sos at local. I have run
```
pip install bash_kernel
python -m bash_kernel.install
pip install sos-bash
python -m sos_notebook.install
```
The error message is:
```
[I 14:54:14.666 NotebookApp] Adapting to protocol v5.1 for kernel 70a92fc4-c0d5-4bc1-a880-5788fa462f16
[IPKernelApp] ERROR | Exception in comm_msg for 2b0b4bf22c684dfd86602226d81b91f2
Traceback (most recent call last):
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 408, in update
    notify_frontend=False)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 258, in find
    update_existing(idx)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 225, in update_existing
    f'Cannot change kernel or language of predefined subkernel {name} {x}')
ValueError: Cannot change kernel or language of predefined subkernel bash subkernel Bash with kernel bash for language Bash with color #E6EEFF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/ipykernel/comm/manager.py", line 111, in comm_msg
    comm.handle_msg(msg)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/ipykernel/comm/comm.py", line 159, in handle_msg
    self._msg_callback(msg)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 543, in handle_frontend_msg
    self.subkernels.update(v)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 412, in update
    f'Failed to locate subkernel {kinfo[0]} with kernerl "{kinfo[1]}" and language "{kinfo[2]}": {e}')
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/logging/__init__.py", line 1318, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/workflow_executor.py", line 41, in emit
    'data': {'text/html': f'<div class="sos_logging sos_{record.levelname.lower()}">{record.levelname}: {msg}</div>'}
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 610, in send_frontend_msg
    elif self._meta['use_iopub']:
KeyError: 'use_iopub'
[IPKernelApp] ERROR | Exception in comm_msg for fe0ea5641541419f8745b94421a14379
Traceback (most recent call last):
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 408, in update
    notify_frontend=False)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 258, in find
    update_existing(idx)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 225, in update_existing
    f'Cannot change kernel or language of predefined subkernel {name} {x}')
ValueError: Cannot change kernel or language of predefined subkernel bash subkernel Bash with kernel bash for language Bash with color #E6EEFF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/ipykernel/comm/manager.py", line 111, in comm_msg
    comm.handle_msg(msg)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/ipykernel/comm/comm.py", line 159, in handle_msg
    self._msg_callback(msg)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 543, in handle_frontend_msg
    self.subkernels.update(v)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 412, in update
    f'Failed to locate subkernel {kinfo[0]} with kernerl "{kinfo[1]}" and language "{kinfo[2]}": {e}')
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/logging/__init__.py", line 1318, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/workflow_executor.py", line 41, in emit
    'data': {'text/html': f'<div class="sos_logging sos_{record.levelname.lower()}">{record.levelname}: {msg}</div>'}
  File "/Users/jma7/anaconda/envs/VariantTools/lib/python3.6/site-packages/sos_notebook/kernel.py", line 610, in send_frontend_msg
    elif self._meta['use_iopub']:
KeyError: 'use_iopub'
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version
```

**Comment by BoPeng** [comment]
I fixed something yesterday so please update to the master or latest release and let me know if the problem persists. The problem was caused by changes in sos so you will have to update sos as well.

**Comment by jma7** [comment]
I ```git pull``` on master and ```pip install . -U``` in both sos and sos-notebook folder. I can still see the same error.

**Comment by BoPeng** [comment]
For whatever reason, the local copy of @jma7 's notebook has kernel info wrong, basically instead of

```
   "kernels": [
    [
     "Bash",
     "bash",
     "Bash",
     "#E6EEFF"
    ],
```
it has
```
   "kernels": [
    [
     "Bash",
     "Bash",
     "Bash",
     "#E6EEFF"
    ],
```
which causes the error. Anyway, sos notebook should be more robust to unknown kernels.

**Comment by BoPeng** [comment]
The error message already described the problem but a bit confusing.

> Cannot change kernel or language of predefined subkernel bash subkernel Bash with kernel bash for language Bash with color #E6EEFF

What is says is that the notebook has language `Bash` with kernel `Bash`, but the local system has language `Bash` with kernel `bash`, and SoS does not know what to do. Assuming the notebook has

```
lang = A, kernel=B
```
it is possible for local system to have
```
lang=A, kernel=new_K
```
which is this case, and
```
lang=new_L, kernel=B
```
which we do not know how to handle either.
