### ISSUE TITLE
sos-papermill no longer works

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#295]
```
sos convert minimal_working_example.ipynb  test.html --execute
WARNING: Option --execute is deprecated. Please use sos-papermill instead.
ERROR: Failed to execute converter ipynb-html: Please install papermill for the use of option --execute.
```

Two issues here: 

1. the command failed even though we have installed papermill
2. It warns about a deprecated option but it is not clear what the alternative is. `sos convert -h` does not help. 

The problem with 1 is perhaps related to papermill new version compatiblity issue :+1: 
```
>>> from papermill.execute import execute_notebook
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/lib/python3.7/site-packages/papermill/__init__.py", line 4, in <module>
    from .execute import execute_notebook
  File "/opt/miniconda3/lib/python3.7/site-packages/papermill/execute.py", line 9, in <module>
    from .engines import papermill_engines
  File "/opt/miniconda3/lib/python3.7/site-packages/papermill/engines.py", line 409, in <module>
    papermill_engines.register_entry_points()
  File "/opt/miniconda3/lib/python3.7/site-packages/papermill/engines.py", line 38, in register_entry_points
    self.register(entrypoint.name, entrypoint.load())
  File "/opt/miniconda3/lib/python3.7/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/opt/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/miniconda3/lib/python3.7/site-packages/sos_papermill/engine.py", line 12, in <module>
    from papermill.preprocess import PapermillExecutePreprocessor
ModuleNotFoundError: No module named 'papermill.preprocess'

```

**Comment by BoPeng** [comment]
So a newer version of papermill no longer has Preprocessor?

**Comment by gaow** [comment]
> So a newer version of papermill no longer has Preprocessor?

Yes there is an open ticket for it https://github.com/vatlab/sos-papermill/issues/9
