### ISSUE TITLE
ImportError: cannot import name 'Sized' from 'collections'

### ISSUE THREAD

**Issue by andrewcrook** [vatlab/sos-notebook#336]
Python 3.10, macOS 12, M1, Jupyter notebooks (6.4.8)
Upon starting jupyter notebook
failes to load kernel and loops looks like a import error

```
Traceback (most recent call last):
  File "/Users/andrew/.asdf/installs/python/3.10.1/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/andrew/.asdf/installs/python/3.10.1/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/andrew/code/Jupyter/.direnv/python-3.10.1/lib/python3.10/site-packages/sos_notebook/kernel.py", line 32, in <module>
    from .completer import SoS_Completer
  File "/Users/andrew/code/Jupyter/.direnv/python-3.10.1/lib/python3.10/site-packages/sos_notebook/completer.py", line 11, in <module>
    from .magics import SoS_Magics
  File "/Users/andrew/code/Jupyter/.direnv/python-3.10.1/lib/python3.10/site-packages/sos_notebook/magics.py", line 11, in <module>
    from collections import Sized, OrderedDict, Sequence
ImportError: cannot import name 'Sized' from 'collections' (/Users/andrew/.asdf/installs/python/3.10.1/lib/python3.10/collections/__init__.py)
```

**Comment by andrewcrook** [comment]
I am fixing right now

**Comment by andrewcrook** [comment]
Pull request #337

**Comment by BoPeng** [comment]
Thanks. I have not tried 3.10 yet so I have not noticed this problem. 

I have merged the PR and will check if there is any pending bug that prevents a new release.
