### ISSUE TITLE
No module named 'jupyter_contrib_core'

### ISSUE THREAD

**Issue by multimeric** [vatlab/sos-notebook#344]
I guess maybe this is missing somewhere as an explicit dependency of the `sos_notebook` package?

I get:
```
$ python -m sos_notebook.install

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/users/allstaff/milton.m/.cache/pypoetry/virtualenvs/slarray-i4sWQy9H-py3.11/lib/python3.11/site-packages/sos_notebook/install.py", line 14, in <module>
    from jupyter_contrib_core.notebook_compat import nbextensions
ModuleNotFoundError: No module named 'jupyter_contrib_core'
```

**Comment by BoPeng** [comment]
You are right. this module is only needed for installation so it was not included in `install_requires`. The conda recipe includes it as installation dependency though.

I have created a PR #345 to add `jupyter_contrib_core` to `install_requires`.
