### ISSUE TITLE
No `__max_procs__` attribute

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#36]
Is SoS Notebook broken? Here is how the error is reproduced:

```
%run -v4
[1]
data = open('/tmp/1.txt'.readlines())
```

I get:

```
DEBUG: Workflow default created with 1 sections: default_1
  File "/opt/miniconda3/lib/python3.6/site-packages/sos_notebook-0.9.11.1-py3.6.egg/sos_notebook/workflow_executor.py", line 365, in runfile
    'max_procs': args.__max_procs__,
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/sos_notebook-0.9.11.1-py3.6.egg/sos_notebook/workflow_executor.py", line 365, in runfile
    'max_procs': args.__max_procs__,
AttributeError: 'Namespace' object has no attribute '__max_procs__'
'Namespace' object has no attribute '__max_procs__'
```

**Comment by BoPeng** [comment]
You need to upgrade `sos`. `python setup.py install` should do that, right?

**Comment by gaow** [comment]
Oh I'm sorry i thought I've done that on this computer! Got too many computers to keep track of :( I instead spent time pull the latest sos-notebook
